In [ ]:
import pandas as pd
df = pd.read_csv("invoices.csv")

/tmp/ipykernel_1407/2971728679.py:2: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("invoices.csv")

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 230548 entries, 0 to 230547
Data columns (total 14 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   InvoiceLineID   230548 non-null  int64
 1   InvoiceID       230548 non-null  int64
 2   StockItemID     230087 non-null  float64
 3   Description     229876 non-null  object
 4   PackageTypeID   230548 non-null  int64
 5   Quantity        230548 non-null  int64
 6   UnitPrice       230548 non-null  float64
 7   TaxRate         230548 non-null  int64
 8   TaxAmount       109623 non-null  float64
 9   LineProfit      230548 non-null  float64
 10  ExtendedPrice   113081 non-null  float64
 11  LastEditedBy    230548 non-null  int64
 12  LastEditedWhen  6 non-null       object
 13  Customer        230548 non-null  object
dtypes: float64(5), int64(6), object(3)
memory usage: 24.6+ MB

In [ ]:
df.describe()

,InvoiceLineID,InvoiceID,StockItemID,PackageTypeID,Quantity,UnitPrice,TaxRate,TaxAmount,LineProfit,ExtendedPrice,LastEditedBy
count,230548.000000,230548.000000,230087.000000,230548.000000,230548.000000,230548.000000,230548.000000,109623.000000,230548.00000,113081.000000,230548.000000
mean,114127.066880,35177.386891,110.181827,7.073638,39.252524,45.539361,14.463409,113.328006,375.38894,740.092626,10.800480
std,65900.142929,20338.920057,63.722514,0.644528,55.193934,139.510031,3.904056,221.866696,753.17041,1705.229089,5.509623
min,1.000000,1.000000,1.000000,1.000000,1.000000,0.660000,-15.000000,0.380000,-645.00000,-999.000000,2.000000
25%,57062.750000,17570.000000,54.000000,7.000000,5.000000,13.000000,15.000000,14.400000,51.00000,89.700000,6.000000
50%,114130.500000,35151.000000,111.000000,7.000000,10.000000,18.000000,15.000000,34.500000,120.00000,248.400000,11.000000
75%,171203.250000,52766.000000,165.000000,7.000000,60.000000,32.000000,15.000000,129.600000,390.00000,919.080000,16.000000
max,228265.000000,70510.000000,227.000000,10.000000,3150.000000,1899.000000,15.000000,14994.000000,9200.00000,114954.000000,20.000000

In [ ]:
df.head()

,InvoiceLineID,InvoiceID,StockItemID,Description,PackageTypeID,Quantity,UnitPrice,TaxRate,TaxAmount,LineProfit,ExtendedPrice,LastEditedBy,LastEditedWhen,Customer
0,1,1,67.0,Ride on toy sedan car (Black) 1/12 scale,7,10,230.0,15,345.0,850.0,2645.0,7,NaN,Stuff by Stew
1,2,2,50.0,Developer joke mug - old C developers never di...,7,9,13.0,15,NaN,76.5,-999.0,7,1/1/2013 12:00,Wholesaler Plus
2,3,2,10.0,USB food flash drive - chocolate bar,7,9,32.0,15,43.2,180.0,331.2,7,NaN,Wholesaler Plus
3,4,3,114.0,Superhero action jacket (Blue) XXL,7,3,30.0,15,NaN,24.0,-999.0,7,NaN,Big Buys Retail
4,5,4,206.0,Permanent marker black 5mm nib (Black) 5mm,7,96,2.7,15,NaN,96.0,NaN,7,1/1/2013 12:00,Terry's Trinkets

In [ ]:
#Q5
df['Customer'].value_counts()

Customer
Terry's Trinkets       85593
Stuff by Stew          62752
Stuf by Stew           31984
Wholesaler Plus        15735
Big Buys Retail        13461
Terry's Trinket         9483
stuff by stew           7068
Dennis Distribution     4472
Name: count, dtype: int64

In [ ]:
#Q6
df.drop(columns = 'LastEditedWhen', inplace = True)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 230548 entries, 0 to 230547
Data columns (total 13 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   InvoiceLineID  230548 non-null  int64
 1   InvoiceID      230548 non-null  int64
 2   StockItemID    230087 non-null  float64
 3   Description    229876 non-null  object
 4   PackageTypeID  230548 non-null  int64
 5   Quantity       230548 non-null  int64
 6   UnitPrice      230548 non-null  float64
 7   TaxRate        230548 non-null  int64
 8   TaxAmount      109623 non-null  float64
 9   LineProfit     230548 non-null  float64
 10  ExtendedPrice  113081 non-null  float64
 11  LastEditedBy   230548 non-null  int64
 12  Customer       230548 non-null  object
dtypes: float64(5), int64(6), object(2)
memory usage: 22.9+ MB

In [ ]:
#Q8
(df['StockItemID'].isna() & df['Description'].isna()).value_counts()

False    230087
True        461
Name: count, dtype: int64

In [ ]:
#Q10
df = df[~(df['StockItemID'].isna() & df['Description'].isna())]
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 230087 entries, 0 to 230547
Data columns (total 13 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   InvoiceLineID  230087 non-null  int64
 1   InvoiceID      230087 non-null  int64
 2   StockItemID    230087 non-null  float64
 3   Description    229876 non-null  object
 4   PackageTypeID  230087 non-null  int64
 5   Quantity       230087 non-null  int64
 6   UnitPrice      230087 non-null  float64
 7   TaxRate        230087 non-null  int64
 8   TaxAmount      109408 non-null  float64
 9   LineProfit     230087 non-null  float64
 10  ExtendedPrice  112858 non-null  float64
 11  LastEditedBy   230087 non-null  int64
 12  Customer       230087 non-null  object
dtypes: float64(5), int64(6), object(2)
memory usage: 24.6+ MB

In [ ]:
#Q11
(df["TaxRate"] > 0).value_counts()

TaxRate
True    230087
Name: count, dtype: int64

In [ ]:
df.loc[df['TaxRate']<0, 'TaxRate']*=-1

In [ ]:
df.describe()

,InvoiceLineID,InvoiceID,StockItemID,PackageTypeID,Quantity,UnitPrice,TaxRate,TaxAmount,LineProfit,ExtendedPrice,LastEditedBy,Tax_Amount
count,230087.000000,230087.000000,230087.000000,230087.000000,230087.000000,230087.000000,230087.000000,230087.000000,230087.000000,112858.000000,230087.000000,230087.000000
mean,114131.169266,35178.644621,110.181827,7.073468,39.247267,45.532654,14.977248,6.591497,375.314843,739.846178,10.799919,112.952119
std,65894.369187,20337.134754,63.722514,0.644395,55.193231,139.461436,0.336518,20.995431,753.072527,1704.618239,5.509919,219.486822
min,1.000000,1.000000,1.000000,1.000000,1.000000,0.660000,10.000000,-284.850000,-645.000000,-999.000000,2.000000,0.375000
25%,57077.500000,17574.000000,54.000000,7.000000,5.000000,13.000000,15.000000,1.950000,51.000000,89.700000,6.000000,14.400000
50%,114131.000000,35151.000000,111.000000,7.000000,10.000000,18.000000,15.000000,2.700000,120.000000,248.400000,11.000000,34.500000
75%,171196.500000,52764.000000,165.000000,7.000000,60.000000,32.000000,15.000000,4.800000,390.000000,919.080000,16.000000,129.600000
max,228265.000000,70510.000000,227.000000,10.000000,3150.000000,1899.000000,15.000000,284.850000,9200.000000,114954.000000,20.000000,14994.000000

In [ ]:
#Q14
df["Tax_Amount"] = (df["UnitPrice"] * df["Quantity"] * df["TaxRate"]/100)
df.head()

,InvoiceLineID,InvoiceID,StockItemID,Description,PackageTypeID,Quantity,UnitPrice,TaxRate,TaxAmount,LineProfit,ExtendedPrice,LastEditedBy,Customer,Tax_Amount
0,1,1,67.0,Ride on toy sedan car (Black) 1/12 scale,7,10,230.0,15,34.500,850.0,2645.0,7,Stuff by Stew,345.00
1,2,2,50.0,Developer joke mug - old C developers never di...,7,9,13.0,15,1.950,76.5,-999.0,7,Wholesaler Plus,17.55
2,3,2,10.0,USB food flash drive - chocolate bar,7,9,32.0,15,4.800,180.0,331.2,7,Wholesaler Plus,43.20
3,4,3,114.0,Superhero action jacket (Blue) XXL,7,3,30.0,15,4.500,24.0,-999.0,7,Big Buys Retail,13.50
4,5,4,206.0,Permanent marker black 5mm nib (Black) 5mm,7,96,2.7,15,0.405,96.0,NaN,7,Terry's Trinkets,38.88

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 230087 entries, 0 to 230547
Data columns (total 14 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   InvoiceLineID  230087 non-null  int64
 1   InvoiceID      230087 non-null  int64
 2   StockItemID    230087 non-null  float64
 3   Description    229876 non-null  object
 4   PackageTypeID  230087 non-null  int64
 5   Quantity       230087 non-null  int64
 6   UnitPrice      230087 non-null  float64
 7   TaxRate        230087 non-null  int64
 8   TaxAmount      230087 non-null  float64
 9   LineProfit     230087 non-null  float64
 10  ExtendedPrice  112858 non-null  float64
 11  LastEditedBy   230087 non-null  int64
 12  Customer       230087 non-null  object
 13  Tax_Amount     230087 non-null  float64
dtypes: float64(6), int64(6), object(2)
memory usage: 26.3+ MB

In [ ]:
df.describe()

,InvoiceLineID,InvoiceID,StockItemID,PackageTypeID,Quantity,UnitPrice,TaxRate,TaxAmount,LineProfit,ExtendedPrice,LastEditedBy,Tax_Amount
count,230087.000000,230087.000000,230087.000000,230087.000000,230087.000000,230087.000000,230087.000000,230087.000000,230087.000000,112858.000000,230087.000000,230087.000000
mean,114131.169266,35178.644621,110.181827,7.073468,39.247267,45.532654,14.977248,6.591497,375.314843,739.846178,10.799919,112.952119
std,65894.369187,20337.134754,63.722514,0.644395,55.193231,139.461436,0.336518,20.995431,753.072527,1704.618239,5.509919,219.486822
min,1.000000,1.000000,1.000000,1.000000,1.000000,0.660000,10.000000,-284.850000,-645.000000,-999.000000,2.000000,0.375000
25%,57077.500000,17574.000000,54.000000,7.000000,5.000000,13.000000,15.000000,1.950000,51.000000,89.700000,6.000000,14.400000
50%,114131.000000,35151.000000,111.000000,7.000000,10.000000,18.000000,15.000000,2.700000,120.000000,248.400000,11.000000,34.500000
75%,171196.500000,52764.000000,165.000000,7.000000,60.000000,32.000000,15.000000,4.800000,390.000000,919.080000,16.000000,129.600000
max,228265.000000,70510.000000,227.000000,10.000000,3150.000000,1899.000000,15.000000,284.850000,9200.000000,114954.000000,20.000000,14994.000000

In [ ]:
#Q15
df["Extended_Price"] = (df["UnitPrice"] * df["Quantity"]) + df["Tax_Amount"]
df.head()

,InvoiceLineID,InvoiceID,StockItemID,Description,PackageTypeID,Quantity,UnitPrice,TaxRate,TaxAmount,LineProfit,ExtendedPrice,LastEditedBy,Customer,Tax_Amount,Extended_Price
0,1,1,67.0,Ride on toy sedan car (Black) 1/12 scale,7,10,230.0,15,34.500,850.0,2645.0,7,Stuff by Stew,345.00,2645.00
1,2,2,50.0,Developer joke mug - old C developers never di...,7,9,13.0,15,1.950,76.5,-999.0,7,Wholesaler Plus,17.55,134.55
2,3,2,10.0,USB food flash drive - chocolate bar,7,9,32.0,15,4.800,180.0,331.2,7,Wholesaler Plus,43.20,331.20
3,4,3,114.0,Superhero action jacket (Blue) XXL,7,3,30.0,15,4.500,24.0,-999.0,7,Big Buys Retail,13.50,103.50
4,5,4,206.0,Permanent marker black 5mm nib (Black) 5mm,7,96,2.7,15,0.405,96.0,NaN,7,Terry's Trinkets,38.88,298.08

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 230087 entries, 0 to 230547
Data columns (total 15 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   InvoiceLineID   230087 non-null  int64
 1   InvoiceID       230087 non-null  int64
 2   StockItemID     230087 non-null  float64
 3   Description     229876 non-null  object
 4   PackageTypeID   230087 non-null  int64
 5   Quantity        230087 non-null  int64
 6   UnitPrice       230087 non-null  float64
 7   TaxRate         230087 non-null  int64
 8   TaxAmount       230087 non-null  float64
 9   LineProfit      230087 non-null  float64
 10  ExtendedPrice   112858 non-null  float64
 11  LastEditedBy    230087 non-null  int64
 12  Customer        230087 non-null  object
 13  Tax_Amount      230087 non-null  float64
 14  Extended_Price  230087 non-null  float64
dtypes: float64(7), int64(6), object(2)
memory usage: 28.1+ MB

In [ ]:
df.describe()

,InvoiceLineID,InvoiceID,StockItemID,PackageTypeID,Quantity,UnitPrice,TaxRate,TaxAmount,LineProfit,ExtendedPrice,LastEditedBy,Tax_Amount,Extended_Price
count,230087.000000,230087.000000,230087.000000,230087.000000,230087.000000,230087.000000,230087.000000,230087.000000,230087.000000,112858.000000,230087.000000,230087.000000,230087.000000
mean,114131.169266,35178.644621,110.181827,7.073468,39.247267,45.532654,14.977248,6.591497,375.314843,739.846178,10.799919,112.952119,867.637267
std,65894.369187,20337.134754,63.722514,0.644395,55.193231,139.461436,0.336518,20.995431,753.072527,1704.618239,5.509919,219.486822,1683.168110
min,1.000000,1.000000,1.000000,1.000000,1.000000,0.660000,10.000000,-284.850000,-645.000000,-999.000000,2.000000,0.375000,2.875000
25%,57077.500000,17574.000000,54.000000,7.000000,5.000000,13.000000,15.000000,1.950000,51.000000,89.700000,6.000000,14.400000,110.400000
50%,114131.000000,35151.000000,111.000000,7.000000,10.000000,18.000000,15.000000,2.700000,120.000000,248.400000,11.000000,34.500000,264.500000
75%,171196.500000,52764.000000,165.000000,7.000000,60.000000,32.000000,15.000000,4.800000,390.000000,919.080000,16.000000,129.600000,993.600000
max,228265.000000,70510.000000,227.000000,10.000000,3150.000000,1899.000000,15.000000,284.850000,9200.000000,114954.000000,20.000000,14994.000000,114954.000000

In [ ]:
#Q18-19
#Use Comments to run either Head, PZS or QZS
average_price = df['Extended_Price'].mean()
std_dev_price = df['Extended_Price'].std()
average_Quantity = df['Quantity'].mean()
std_dev_Quantity = df['Quantity'].std()
df['Price_Z-Score'] = ((df['Extended_Price']- average_price)/ std_dev_price)
df['Quantity_Z-Score'] = ((df['Quantity']- average_Quantity)/ std_dev_Quantity)
PZS_POS=(df['Price_Z-Score'] >= 3)
PZS_NEG=(df['Price_Z-Score'] <= -3)
QZS_POS=(df['Quantity_Z-Score'] >= 3)
QZS_NEG=(df['Quantity_Z-Score'] <= -3)
df.head()
(PZS_POS + PZS_NEG).sum()
# (QZS_POS + QZS_NEG).sum()

np.int64(4522)

In [ ]:
#Q20/21
df.drop_duplicates(subset=['InvoiceLineID'], inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 227811 entries, 0 to 229321
Data columns (total 17 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   InvoiceLineID     227811 non-null  int64
 1   InvoiceID         227811 non-null  int64
 2   StockItemID       227811 non-null  float64
 3   Description       227604 non-null  object
 4   PackageTypeID     227811 non-null  int64
 5   Quantity          227811 non-null  int64
 6   UnitPrice         227811 non-null  float64
 7   TaxRate           227811 non-null  int64
 8   TaxAmount         227811 non-null  float64
 9   LineProfit        227811 non-null  float64
 10  ExtendedPrice     111770 non-null  float64
 11  LastEditedBy      227811 non-null  int64
 12  Customer          227811 non-null  object
 13  Tax_Amount        227811 non-null  float64
 14  Extended_Price    227811 non-null  float64
 15  Price_Z-Score     227811 non-null  float64
 16  Quantity_Z-Score  227811 non-null  float64
dtypes: float64(9), int64(6), object(2)
memory usage: 31.3+ MB

In [ ]:
#22
df[df['Quantity'] == 3150]

,InvoiceLineID,InvoiceID,StockItemID,Description,PackageTypeID,Quantity,UnitPrice,TaxRate,TaxAmount,LineProfit,ExtendedPrice,LastEditedBy,Customer,Tax_Amount,Extended_Price,Price_Z-Score,Quantity_Z-Score
157514,157515,48531,188.0,3 kg Courier post bag (White) 300x190x95mm,7,3150,0.66,15,0.099,67.5,2390.85,16,Wholesaler Plus,311.85,2390.85,0.904968,56.361127

In [ ]:
df[df['LineProfit'] == 9200]

,InvoiceLineID,InvoiceID,StockItemID,Description,PackageTypeID,Quantity,UnitPrice,TaxRate,TaxAmount,LineProfit,ExtendedPrice,LastEditedBy,Customer,Tax_Amount,Extended_Price,Price_Z-Score,Quantity_Z-Score
777,778,313,161.0,20 mm Double sided bubble wrap 50m,7,100,108.0,15,16.2,9200.0,12420.0,20,Terry's Trinkets,1620.0,12420.0,6.863463,1.100728
1228,1229,457,161.0,20 mm Double sided bubble wrap 50m,7,100,108.0,15,16.2,9200.0,NaN,8,Terry's Trinkets,1620.0,12420.0,6.863463,1.100728
1476,1477,528,161.0,20 mm Double sided bubble wrap 50m,7,100,108.0,15,16.2,9200.0,NaN,19,Wholesaler Plus,1620.0,12420.0,6.863463,1.100728
2463,2464,816,161.0,20 mm Double sided bubble wrap 50m,7,100,108.0,15,16.2,9200.0,12420.0,9,Big Buys Retail,1620.0,12420.0,6.863463,1.100728
4402,4403,1399,161.0,20 mm Double sided bubble wrap 50m,7,100,108.0,15,16.2,9200.0,NaN,4,Stuff by Stew,1620.0,12420.0,6.863463,1.100728
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
217311,217312,67122,161.0,20 mm Double sided bubble wrap 50m,7,100,108.0,15,16.2,9200.0,NaN,16,Stuff by Stew,1620.0,12420.0,6.863463,1.100728
217897,217898,67309,161.0,20 mm Double sided bubble wrap 50m,7,100,108.0,15,16.2,9200.0,NaN,18,Stuff by Stew,1620.0,12420.0,6.863463,1.100728
221954,221955,68582,161.0,20 mm Double sided bubble wrap 50m,7,100,108.0,15,16.2,9200.0,NaN,13,Stuff by Stew,1620.0,12420.0,6.863463,1.100728
226950,226951,70108,161.0,20 mm Double sided bubble wrap 50m,7,100,108.0,15,16.2,9200.0,12420.0,7,Terry's Trinkets,1620.0,12420.0,6.863463,1.100728
228174,228175,70484,161.0,20 mm Double sided bubble wrap 50m,7,100,108.0,15,16.2,9200.0,NaN,3,Terry's Trinkets,1620.0,12420.0,6.863463,1.100728

In [ ]:
df.describe()

,InvoiceLineID,InvoiceID,StockItemID,PackageTypeID,Quantity,UnitPrice,TaxRate,TaxAmount,LineProfit,ExtendedPrice,LastEditedBy,Tax_Amount,Extended_Price,Price_Z-Score,Quantity_Z-Score
count,227811.000000,227811.000000,227811.000000,227811.000000,227811.000000,227811.000000,227811.000000,227811.000000,227811.000000,111770.000000,227811.000000,227811.000000,227811.000000,227811.000000,227811.000000
mean,114138.092138,35180.773211,110.183512,7.073600,39.251366,45.584056,14.977284,6.597729,375.497371,740.300099,10.798105,113.027735,868.215594,0.000344,0.000074
std,65889.140423,20335.528618,63.730057,0.644306,55.207157,139.811797,0.336252,21.048346,753.950915,1706.341928,5.510464,219.805264,1685.608572,1.001450,1.000252
min,1.000000,1.000000,1.000000,1.000000,1.000000,0.660000,10.000000,-284.850000,-645.000000,-999.000000,2.000000,0.375000,2.875000,-0.513771,-0.692970
25%,57082.500000,17575.500000,54.000000,7.000000,5.000000,13.000000,15.000000,1.950000,51.000000,89.700000,6.000000,14.400000,110.400000,-0.449888,-0.620498
50%,114135.000000,35152.000000,111.000000,7.000000,10.000000,18.000000,15.000000,2.700000,120.000000,248.400000,11.000000,34.500000,264.500000,-0.358335,-0.529907
75%,171192.500000,52762.500000,165.000000,7.000000,60.000000,32.000000,15.000000,4.800000,390.000000,919.080000,16.000000,129.600000,993.600000,0.074837,0.376001
max,228265.000000,70510.000000,227.000000,10.000000,3150.000000,1899.000000,15.000000,284.850000,9200.000000,114954.000000,20.000000,14994.000000,114954.000000,67.780730,56.361127

In [ ]:
#Q25
df.groupby("Description")["Quantity"].mean().sort_values(ascending=False)

Description
Black and orange fragile despatch tape 48mmx75m                                          199.526012
Black and orange fragile despatch tape 48mmx100m                                         199.148148
Clear packaging tape 48mmx75m                                                            145.313761
3 kg Courier post bag (White) 300x190x95mm                                               144.012116
Shipping carton (Brown) 356x356x279mm                                                    141.612150
                                                                                            ...
USB food flash drive - hamburger                                                           5.327273
Superhero action jacket (Blue) L                                                           5.317073
DBA joke mug - SELECT caffeine FROM mug (Black)                                            5.283915
Developer joke mug - understanding recursion requires understanding recursion (Black)      5.277831
Superhero action jacket (Blue) XXL                                                         5.211186
Name: Quantity, Length: 227, dtype: float64